
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author usuario
 */
public class FmrClientes2 extends javax.swing.JPanel {

    /**
     * Creates new form FmrClientes2
     */
    public FmrClientes2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltelefono = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        lblcedula = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblnombres = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblapellidos = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        lblemail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jcliente = new javax.swing.JTable();

        setBackground(new java.awt.Color(242, 239, 223));

        lbltelefono.setForeground(new java.awt.Color(51, 51, 51));
        lbltelefono.setText("Telefono");

        txtcedula.setEditable(false);
        txtcedula.setBackground(new java.awt.Color(208, 217, 212));
        txtcedula.setColumns(5);
        txtcedula.setForeground(new java.awt.Color(89, 85, 76));
        txtcedula.setText("ej.: xxxxxxxxx-x");
        txtcedula.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(208, 217, 212));
        jTextField6.setForeground(new java.awt.Color(89, 85, 76));
        jTextField6.setText("Buscar.....");
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        txtnombres.setBackground(new java.awt.Color(208, 217, 212));
        txtnombres.setForeground(new java.awt.Color(89, 85, 76));
        txtnombres.setText("ej.: Fernando");
        txtnombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });

        txtapellidos.setBackground(new java.awt.Color(208, 217, 212));
        txtapellidos.setForeground(new java.awt.Color(89, 85, 76));
        txtapellidos.setText("ej.: Mero");
        txtapellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtemail.setBackground(new java.awt.Color(208, 217, 212));
        txtemail.setForeground(new java.awt.Color(89, 85, 76));
        txtemail.setText("ej.: example@gmail.com");
        txtemail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txttelefono.setBackground(new java.awt.Color(208, 217, 212));
        txttelefono.setForeground(new java.awt.Color(89, 85, 76));
        txttelefono.setText("ej.: 0994538638");
        txttelefono.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(89, 85, 76));
        btnActualizar.setForeground(new java.awt.Color(208, 217, 212));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblcedula.setForeground(new java.awt.Color(51, 51, 51));
        lblcedula.setText("Cedula");
        lblcedula.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnEliminar.setBackground(new java.awt.Color(89, 85, 76));
        btnEliminar.setForeground(new java.awt.Color(208, 217, 212));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblnombres.setForeground(new java.awt.Color(51, 51, 51));
        lblnombres.setText("Nombres");

        btnEnviar.setBackground(new java.awt.Color(89, 85, 76));
        btnEnviar.setForeground(new java.awt.Color(208, 217, 212));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblapellidos.setForeground(new java.awt.Color(51, 51, 51));
        lblapellidos.setText("Apellidos");

        btnNuevo.setBackground(new java.awt.Color(89, 85, 76));
        btnNuevo.setForeground(new java.awt.Color(208, 217, 212));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblemail.setForeground(new java.awt.Color(51, 51, 51));
        lblemail.setText("E-mail");

        Jcliente.setBackground(new java.awt.Color(208, 217, 212));
        Jcliente.setForeground(new java.awt.Color(89, 85, 76));
        Jcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombres", "Apellidos", "E-mail", "Telefono"
            }
        ));
        Jcliente.setGridColor(new java.awt.Color(89, 85, 76));
        Jcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jcliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnombres)
                        .addGap(18, 18, 18)
                        .addComponent(txtnombres))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcedula)
                        .addGap(30, 30, 30)
                        .addComponent(txtcedula))
                    .addComponent(jTextField6)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapellidos)
                            .addComponent(lbltelefono)
                            .addComponent(lblemail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemail)
                            .addComponent(txtapellidos)
                            .addComponent(txttelefono))))
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedula)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombres)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapellidos)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEnviar)
                    .addComponent(btnNuevo))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            // TODO add your handling code here:
            this.actualizar();
        } catch (Exception ex) {
            Logger.getLogger(FmrClientes2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void JclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JclienteMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_JclienteMouseClicked

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
public void nuevo() {
        try {
            ClienteBeans cb = new ClienteBeans();
            txtcedula.setText("");
            txtnombres.setText("");
            txtapellidos.setText("");
            txtemail.setText("");
            txttelefono.setText("");
            this.mostrar(Jcliente, "SELECT * FROM clientes c");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }

    public void enviar() {
        try {
            ClienteBeans cb = new ClienteBeans();
            cb.setId_Cliente(Integer.parseInt(txtcedula.getText()));
            cb.setNombre(txtnombres.getText());
            cb.setApellido(txtapellidos.getText());
            cb.setEmail(txtemail.getText());
            cb.setTelefono(txttelefono.getText());
            cb.insertar_cliente();
            this.mostrar(Jcliente, "SELECT * FROM clientes c");
            JOptionPane.showMessageDialog(null, "La infromacion se guardo con exito!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Transaccion: " + e.toString());
        }
    }
    
    private void MouseClick(){
        int fila=Jcliente.getSelectedRow();
        txtcedula.setText(Jcliente.getModel().getValueAt(fila,0).toString());
        txtnombres.setText(Jcliente.getModel().getValueAt(fila,1).toString());
        txtapellidos.setText(Jcliente.getModel().getValueAt(fila,2).toString());
        txtemail.setText(Jcliente.getModel().getValueAt(fila,3).toString());
        txttelefono.setText(Jcliente.getModel().getValueAt(fila,4).toString());
        
    }
    
    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            ClienteBeans cb = new ClienteBeans();
            ResultSet rs;
            DefaultTableModel model = new DefaultTableModel();
            JT.setModel(model);
            rs = cb.consultarTabla(sql);
            ResultSetMetaData rsmd;
            rsmd = rs.getMetaData();
            int cantcolum = rsmd.getColumnCount();
            for (int i = 0; i < cantcolum; i++) {
                model.addColumn(rsmd.getColumnLabel(i+1));
                
            }
            while (rs.next()) {
                Object[] colum = new Object[cantcolum];
                for (int i = 0; i < cantcolum; i++) {
                    colum[i] = rs.getObject(i + 1);
                    
                }
                model.addRow(colum);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }
    public void actualizar() throws Exception{
        try {
            ClienteBeans cb = new ClienteBeans();
            cb.setId_Cliente(Integer.parseInt(txtcedula.getText()));
            cb.setNombre(txtnombres.getText());
            cb.setApellido(txtapellidos.getText());
            cb.setEmail(txtemail.getText());
            cb.setTelefono(txttelefono.getText());
            cb.actulizar_cliente();
            this.mostrar(Jcliente, "SELECT * FROM clientes c");
            JOptionPane.showMessageDialog(null, "La actualizacion fue exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " +e.toString());
        }

    }
    public void eliminar(){
        try {
            ClienteBeans cb = new ClienteBeans();
            cb.setId_Cliente(Integer.parseInt(txtcedula.getText()));
            cb.actulizar_cliente();
            this.mostrar(Jcliente, "SELECT * FROM clientes c");
            JOptionPane.showMessageDialog(null, "La actualizacion fue exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " +e.toString());
        }
    }
    

    //introducimos los modulos
    public void item(JComboBox modu) {
        modu.addItem("Salas");
        
    }
    
    public void Modulo(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jcliente;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
