
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author usuario
 */
public class FrmSalas extends javax.swing.JFrame {

    SalaBeans sl;

    /**
     * Creates new form FrmSalas
     */
    public FrmSalas() throws Exception {
        initComponents();
        sl = new SalaBeans();
        this.mostrar(JTsalas, "SELECT sala_id as \"Cod Sala\",nombre as \"Sala\", capacidad as \"Asientos\" FROM salas s;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblnombresala = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblcapacidad = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcapacidad = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTsalas = new javax.swing.JTable();
        btnenviar = new javax.swing.JButton();
        Retorno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salas");

        lblID.setBackground(new java.awt.Color(208, 217, 212));
        lblID.setForeground(new java.awt.Color(51, 51, 51));
        lblID.setText("ID");

        jButton3.setBackground(new java.awt.Color(89, 85, 76));
        jButton3.setForeground(new java.awt.Color(208, 217, 212));
        jButton3.setText("Actualizar");
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setSelected(true);
        jButton3.setVerifyInputWhenFocusTarget(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblnombresala.setBackground(new java.awt.Color(208, 217, 212));
        lblnombresala.setForeground(new java.awt.Color(51, 51, 51));
        lblnombresala.setText("Nombre");

        jButton4.setBackground(new java.awt.Color(89, 85, 76));
        jButton4.setForeground(new java.awt.Color(208, 217, 212));
        jButton4.setText("Eliminar");
        jButton4.setFocusPainted(false);

        lblcapacidad.setBackground(new java.awt.Color(208, 217, 212));
        lblcapacidad.setForeground(new java.awt.Color(51, 51, 51));
        lblcapacidad.setText("Cantidad");

        txtid.setBackground(new java.awt.Color(208, 217, 212));
        txtid.setForeground(new java.awt.Color(89, 85, 76));
        txtid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtnombre.setBackground(new java.awt.Color(208, 217, 212));
        txtnombre.setForeground(new java.awt.Color(89, 85, 76));
        txtnombre.setText("A-1");
        txtnombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtcapacidad.setBackground(new java.awt.Color(208, 217, 212));
        txtcapacidad.setForeground(new java.awt.Color(89, 85, 76));
        txtcapacidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField4.setBackground(new java.awt.Color(208, 217, 212));
        jTextField4.setForeground(new java.awt.Color(89, 85, 76));
        jTextField4.setText("Buscar...");
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnnuevo.setBackground(new java.awt.Color(89, 85, 76));
        btnnuevo.setForeground(new java.awt.Color(208, 217, 212));
        btnnuevo.setText("Nuevo");
        btnnuevo.setBorderPainted(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        JTsalas.setBackground(new java.awt.Color(208, 217, 212));
        JTsalas.setForeground(new java.awt.Color(89, 85, 76));
        JTsalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Cantidad"
            }
        ));
        JTsalas.setGridColor(new java.awt.Color(89, 85, 76));
        JTsalas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JTsalasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JTsalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTsalasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTsalas);

        btnenviar.setBackground(new java.awt.Color(89, 85, 76));
        btnenviar.setForeground(new java.awt.Color(208, 217, 212));
        btnenviar.setText("Enviar");
        btnenviar.setFocusPainted(false);
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        Retorno.setBackground(new java.awt.Color(89, 85, 76));
        Retorno.setForeground(new java.awt.Color(208, 217, 212));
        Retorno.setText("Regresar");
        Retorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetornoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcapacidad)
                        .addGap(25, 25, 25)
                        .addComponent(txtcapacidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addGap(62, 62, 62)
                        .addComponent(txtid))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnombresala)
                        .addGap(29, 29, 29)
                        .addComponent(txtnombre))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnenviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnnuevo)
                        .addGap(4, 4, 4)
                        .addComponent(Retorno))
                    .addComponent(jTextField4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombresala)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcapacidad)
                    .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnuevo)
                    .addComponent(btnenviar)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(Retorno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            this.Actualizar();
        } catch (Exception ex) {
            Logger.getLogger(FrmSalas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void JTsalasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JTsalasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JTsalasAncestorAdded

    private void JTsalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTsalasMouseClicked
        // TODO add your handling code here:
        this.MouseClick();
    }//GEN-LAST:event_JTsalasMouseClicked

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        // TODO add your handling code here:
        this.enviar();
    }//GEN-LAST:event_btnenviarActionPerformed

    private void RetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornoActionPerformed
        Inicio in;
        try {
            in = new Inicio();
            in.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(FrmSalas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RetornoActionPerformed


    public void nuevo() {
        try {
            txtid.setText("" + sl.incremento());
            txtnombre.setText("");
            txtcapacidad.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }

    }

    public void enviar() {
        try {
            sl.setSala_id((Integer.parseInt(txtid.getText())));
            sl.setNombre(txtnombre.getText());
            sl.setCapacidad(txtcapacidad.getText());
            sl.insertar_salas();
            this.mostrar(JTsalas, "SELECT sala_id as \"Cod Sala\",nombre as \"Sala\", capacidad as \"Asientos\" FROM salas s;");
            JOptionPane.showMessageDialog(null, "La Transaccion fue Exitosa!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror en la Transaccion" + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable JT, String sql) {
        try {
            ResultSet rs;
            DefaultTableModel model = new DefaultTableModel();
            JT.setModel(model);
            rs = sl.consultarTabla(sql);
            ResultSetMetaData rsmd;
            rsmd = rs.getMetaData();
            int cantcolum = rsmd.getColumnCount();
            for (int i = 0; i < cantcolum; i++) {
                model.addColumn(rsmd.getColumnLabel(i + 1));

            }
            while (rs.next()) {
                Object[] colum = new Object[cantcolum];
                for (int i = 0; i < cantcolum; i++) {
                    colum[i] = rs.getObject(i + 1);

                }
                model.addRow(colum);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Mostrar" + e.toString());
        }

    }

    private void MouseClick() {
        int fila = JTsalas.getSelectedRow();
        txtid.setText(JTsalas.getModel().getValueAt(fila, 0).toString());
        txtnombre.setText(JTsalas.getModel().getValueAt(fila, 1).toString());
        txtcapacidad.setText(JTsalas.getModel().getValueAt(fila, 3).toString());

    }

    public void Actualizar() throws Exception {
        try {
            sl.setSala_id((Integer.parseInt(txtid.getText())));
            sl.setNombre(txtnombre.getText());
            sl.setCapacidad(txtcapacidad.getText());
            sl.actulizar_salas();

            this.mostrar(JTsalas, "SELECT sala_id as \"Cod Sala\",nombre as \"Sala\", capacidad as \"Asientos\" FROM salas s;");
            JOptionPane.showMessageDialog(null, "La Transaccion fue Exitosa!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror en la Transaccion" + e.toString());
        }
    }

    public void eliminar() {
        try {
            sl.setSala_id((Integer.parseInt(txtid.getText())));
            sl.actulizar_salas();
            this.mostrar(JTsalas, "SELECT sala_id as \"Cod Sala\",nombre as \"Sala\", capacidad as \"Asientos\" FROM salas s;");
            JOptionPane.showMessageDialog(null, "La actualizacion fue exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTsalas;
    private javax.swing.JButton Retorno;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblcapacidad;
    private javax.swing.JLabel lblnombresala;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
